apiVersion: v1
kind: Service
metadata:
  name: dev-service
  namespace: dev  
spec:
  type: ClusterIP
  selector:
    app: nginx-dev
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: staging-service
  namespace: staging  
spec:
  type: ClusterIP
  selector:
    app: nginx-staging
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prod-service
  namespace: prod  
spec:
  type: ClusterIP
  selector:
    app: nginx-prod
  ports:
    - port: 80
      targetPort: 80
